#!/usr/bin/env ruby

lib = File.expand_path("../../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "spotgram"

mirror_chat = ENV.fetch("SPOTGRAM_MIRROR_TO_CHAT", nil)
api_key = ENV.fetch("SPOTGRAM_API_KEY")
admin_id = Integer(ENV.fetch("SPOTGRAM_ADMIN_ID"))

Spotgram::Bot.new(api_key, admin_id, mirror_to_chat_id: mirror_chat).run
